### ISSUE TITLE
استفاده از پورت‌هایی غیر از 443

### ISSUE THREAD

**Issue by esisalim** [Surfboardv2ray/v2ray-refiner#1]
سلام ارادت، امکان نداره از v2ray-refiner روی پورت‌هایی غیر از 443 استفاده کرد؟
به دلیل محدودیت ورکر و اینکه نمیشه بیشتر از یه کانفیگ با یه پورت ساخت
راهی نداره بتونیم از پورتای دیگه استفاده کنیم؟ یا نمیشه از rules داخل کلادفلر استفاده کنیم؟

**Comment by Surfboardv2ray** [comment]
> سلام ارادت، امکان نداره از v2ray-refiner روی پورت‌هایی غیر از 443 استفاده کرد؟ به دلیل محدودیت ورکر و اینکه نمیشه بیشتر از یه کانفیگ با یه پورت ساخت راهی نداره بتونیم از پورتای دیگه استفاده کنیم؟ یا نمیشه از rules داخل کلادفلر استفاده کنیم؟

سلام، درود بر شما. احتمالا روی سایر پورت های TLS کلادفلیر هم امکان پذیر باشه. میتونیم پورت رو آزاد بذاریم و شما کانفیگ‌های با پورت های پشتیبانی شده رو وارد کنید، اما برخی از دوستان به اشتباه با پورت های غیرمعتبر کانفیگ میزنن و پیام میذارن که کار نمیکنه. در هر صورت برای حل این مشکل، متغیر `allowedPorts` با مقدار پیش فرض پورت های TLS رو (443, 8443, 2053, 2083, 2087, 2096) به اسکریپت اضافه میکنیم.

اگر خواستید بقیه پورت‌ها رو هم امتحان کنید، میتونید:
* پورت مورد نظر رو به بخش `allowedPorts` اضافه و تست کنید، یا 
* برای برداشتن کلی محدودیت پورت کافیه بخشی از اسکریپت که باعث این اخطار هست، یعنی:
```bash
  // Check if the input port is allowed
  if (!allowedPorts.includes(url.port)) {
    throw new Error('Config must use a Cloudflare TLS Port (443, 8443, 2053, 2083, 2087, or 2096) to proceed');
  }
```
  
از هر سه قسمت vmess و vless و trojan حذف و سایر پورت‌ها رو هم تست کنید.

**Comment by esisalim** [comment]
سلام مجدد..
روی پورتهای دیگه https تست کردم ولی کار نمیکنه، گفته بودید احتمالا کار کنه،‌دلیل خاصی داره که فقط روی 443 کار میکنه؟
پورتی که داخل پنل هست حتما باید 443 باشه ولی داخل نرم افزار میشه پورت رو عوض کرد
به خاطر همین اجازه نمیده داخل پنل بیشتر از یه کانفیگ ساخت

**Comment by esisalim** [comment]
آقا بازم تشکر میکنم بابت پروژه فوق‌العادتون
من تونستم از بقیه پورت‌های کلاد فلر استفاده کنم
فقط لازمه تو قسمت origin rules تمام ترافیک ورودی به دامنه‌تون رو انتقال بدید به پورت مورد نظر
