### ISSUE TITLE
Cloudflare 1101 Error

### ISSUE THREAD

**Issue by qar4al** [Surfboardv2ray/v2ray-refiner#3]
Please fix the problem of error 1101 Cloudflare.

![75faa111683ad53ff70998fa9524934d241006a1](https://github.com/user-attachments/assets/39060fab-6a74-4097-87ac-14e3fab13c85)

**Comment by Surfboardv2ray** [comment]
> Please fix the problem of error 1101 Cloudflare.
> 
> ![75faa111683ad53ff70998fa9524934d241006a1](https://private-user-images.githubusercontent.com/63839880/397253322-39060fab-6a74-4097-87ac-14e3fab13c85.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ4ODEwOTMsIm5iZiI6MTczNDg4MDc5MywicGF0aCI6Ii82MzgzOTg4MC8zOTcyNTMzMjItMzkwNjBmYWItNmE3NC00MDk3LTg3YWMtMTRlM2ZhYjEzYzg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIyVDE1MTk1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViMGNlNGQzYmJjMmY2MTczMjM1MDk5YjA0ZTFmNzllMmY2ZmRhOTFlNDMxNDhiOWRlOThjODNiYzNiZWE2Y2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BSKWhughnQFctxZh4BrA1MjkYMduM-REIYXUA_fCJV4)

Hello. Unfortunately, with the latest update (December 3rd) to [Cloudflare Terms](https://www.cloudflare.com/en-gb/terms/), it's against the Self-Serve Subscription Agreement to use the Services to provide a virtual private network or other similar proxy services. However, you could [try this workaround](https://www.youtube.com/watch?v=ybAu9ZlR6qM).
