### ISSUE TITLE
حل خطا ها

### ISSUE THREAD

**Issue by qar4al** [Surfboardv2ray/v2ray-refiner#4]
چطور میشه این خطا ها رو رفع کرد . بیشتر از درخواست موفق درخواست خطاس

![image](https://github.com/user-attachments/assets/222ce12c-d279-432f-a3af-d48e2e2244f8)

**Comment by Surfboardv2ray** [comment]
> چطور میشه این خطا ها رو رفع کرد . بیشتر از درخواست موفق درخواست خطاس
> 
> ![image](https://private-user-images.githubusercontent.com/63839880/399054461-222ce12c-d279-432f-a3af-d48e2e2244f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU1NzYzMzksIm5iZiI6MTczNTU3NjAzOSwicGF0aCI6Ii82MzgzOTg4MC8zOTkwNTQ0NjEtMjIyY2UxMmMtZDI3OS00MzJmLWEzYWYtZDQ4ZTJlMjI0NGY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjMwVDE2MjcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiYjE1YWNjN2U2ODE3YmE2NWQ5ZTMzZGQwZThjNjFhYzc2NGRmYTE1ZGU5YTAyMTA2YTVjMTM3MDhkOWIzMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7mIHVzJI4GnvHJa05buIY_IoNVkR8THzrEpYqG8QYA0)

سلام، خطاها مختص این اسکریپت نیست و احتمالا بر روی پنل‌های دیگه هم مورد مشابهی رخ بده. علتش نامشخص هست اما ممکنه به دلیل اختلال روی ورکر یا pages، و یا آیپی تمیز باشه
